type: object
properties:
  totalElements:
    type: integer
    format: int64
  totalPages:
    type: integer
    format: int32
  currentPage:
    type: integer
    format: int32
    minimum: 0
    exclusiveMinimum: false
    example: 0
  pageSize:
    type: integer
    format: int32
    minimum: 1
    exclusiveMinimum: false
    example: 10
  content:
    type: array
    items:
      type: object
      $ref: './InventorylineDto.yaml'


  
