type: object
description: 'A product formated in the system'
properties:
  id:
    type: integer
    format: int64
  pfPicture:
    type: string
  pfProduct:
    type: object
    $ref: '../../product/dto/ProductDto.yaml'
  pfFormat:
    type: object
    $ref: '../../format/dto/FormatDto.yaml'
  
