delete:
  summary: Path used to delete a inventoryline in the system with its id
  operationId: deleteInventorylineById
  parameters:
    - in: path
      name: id
      schema:
        type: integer
        format: int64
      required: true
      description: The id that represent the Inventoryline to delete. It's compulsory if not the operation can't proceed
  responses:
    '200':
      description: Inventoryline deleted successfully
      content:
        application/json:
          schema:
            type: boolean
    '400':
      description: Bad request. Currency ID must be an integer and larger than 0.
    '401':
      description: Authorization information is missing or invalid.
    '403':
      description: The user who ask the ressource is Forbidden.
    '404':
      description: The expected ressource is not found.
    '500':
      description: Unexpected error at the server side.
summary: Represents a route used to delete a inventoryline for this system
description: Delete an existing inventoryline in the system