post:
  summary: Path used to list Inventoryline page by page that respect certain criteria. With the Page object, we can configure the page number and size that we want
  operationId: getInventorylinePage
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../../general/dto/FilterRequest.yaml' #FilterRequest
  responses:
    '200':
      description: Inventoryline page found successfully
      content:
        application/json:
          schema:
            type: object
            $ref: '../dto/PageofInventorylineDto.yaml'