post:
  summary: Path used to list inventoryline that respect certain criteria. A criteria is an instance of a Filter object
  operationId: getInventorylineList
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../../general/dto/FilterRequest.yaml' #FilterRequest
  responses:
    '200':
      description: Inventoryline list found successfully
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              $ref: '../dto/InventorylineDto.yaml'

