type: object
description: 'An Inventory used in the system'
properties:
  invComment:
    type: string
  invDate:
    type: string
    format: datetime
  invCode:
    type: string
    example: I0000
  invPos:
    type: object
    $ref: '../../../pos/pos/dto/PointofsaleDto.yaml'
  
