type: object
description: 'A product in the system'
properties:
  prodName:
    type: string
  prodCode:
    type: string
  prodDescription:
    type: string
  prodAlias:
    type: string
  prodPerishable:
    type: boolean
  prodCat:
    type: object
    $ref: '../../category/dto/CategoryDto.yaml'
  
